export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FALL = "CREATE_ORDER_FALL"

export const CREATE_ORDERS_REQUEST = "CREATE_ORDERS_REQUEST"
export const CREATE_ORDERS_SUCCESS = "CREATE_ORDERS_SUCCESS"
export const CREATE_ORDERS_FALL = "CREATE_ORDERS_FALL"

export const CLEAR_ERROR = "CLEAR_ERROR"